#!/usr/bin/env bash
# BirdNET-Pi Web Interface Installer
# Handles both fresh installs and migrations from PHP
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }
echo_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Determine paths
if [ -z "$HOME" ]; then
    HOME=$(getent passwd "$USER" | cut -d: -f6)
fi
BIRDNET_DIR="${BIRDNET_DIR:-$HOME/BirdNET-Pi}"
CONFIG_FILE="/etc/birdnet/birdnet.conf"

# Detection functions
is_fresh_install() {
    # Fresh install if no config file exists
    [ ! -f "$CONFIG_FILE" ]
}

is_base_installed() {
    # Base is installed if Python venv exists and has required packages
    [ -d "$BIRDNET_DIR/birdnet" ] && [ -f "$BIRDNET_DIR/birdnet/bin/python3" ]
}

is_php_installed() {
    # PHP interface is installed if php-fpm is present
    systemctl list-unit-files | grep -q php.*fpm 2>/dev/null
}

has_new_web_interface() {
    # New web interface is installed if FastAPI backend exists and service is enabled
    [ -f "$BIRDNET_DIR/backend/app/main.py" ] && systemctl is-enabled birdnet-web &>/dev/null
}

# Installation functions
install_nodejs() {
    echo_step "Installing Node.js..."
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
        if [ "$NODE_VERSION" -ge 18 ]; then
            echo_info "Node.js $(node -v) already installed"
            return 0
        fi
    fi
    
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    echo_info "Node.js $(node -v) installed"
}

install_backend_deps() {
    echo_step "Installing Python backend dependencies..."
    if [ ! -f "$BIRDNET_DIR/backend/requirements.txt" ]; then
        echo_error "Backend requirements.txt not found"
        return 1
    fi
    
    "$BIRDNET_DIR/birdnet/bin/pip" install -q -r "$BIRDNET_DIR/backend/requirements.txt"
    echo_info "Backend dependencies installed"
}

build_frontend() {
    echo_step "Building frontend..."
    cd "$BIRDNET_DIR/frontend"
    
    # Install npm dependencies
    # Use 'npm install' instead of 'npm ci' in case package-lock.json is missing
    if [ -f "package-lock.json" ]; then
        npm ci --silent
    else
        echo_info "No package-lock.json found, running npm install..."
        npm install
    fi
    
    # Build for production
    npm run build
    
    echo_info "Frontend built successfully"
}

install_systemd_service() {
    echo_step "Installing systemd service..."
    
    # Create service file with correct user
    cat << EOF | sudo tee /etc/systemd/system/birdnet-web.service > /dev/null
[Unit]
Description=BirdNET-Pi Web Interface
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${USER}
Group=${USER}
WorkingDirectory=${BIRDNET_DIR}/backend
Environment="PATH=${BIRDNET_DIR}/birdnet/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=${BIRDNET_DIR}/birdnet/bin/uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 2
Restart=always
RestartSec=10

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=birdnet-web

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable birdnet-web
    echo_info "Systemd service installed"
}

update_caddy_config() {
    echo_step "Updating Caddy configuration..."
    
    # Backup existing config
    if [ -f /etc/caddy/Caddyfile ]; then
        sudo cp /etc/caddy/Caddyfile /etc/caddy/Caddyfile.backup.$(date +%Y%m%d%H%M%S)
    fi
    
    # Get password hash if set
    source "$CONFIG_FILE" 2>/dev/null || true
    
    if [ -n "${CADDY_PWD}" ]; then
        HASHWORD=$(caddy hash-password --plaintext "${CADDY_PWD}")
        AUTH_BLOCK="
  # Legacy parity: protect stream and shell/log access paths with HTTP basic auth
  basicauth /stream* {
    birdnet ${HASHWORD}
  }
  basicauth /log* {
    birdnet ${HASHWORD}
  }
  basicauth /terminal* {
    birdnet ${HASHWORD}
  }
  basicauth /api/config* {
    birdnet ${HASHWORD}
  }
  @protected_system {
    path /api/system*
    not path /api/system/public-status*
  }
  basicauth @protected_system {
    birdnet ${HASHWORD}
  }
  basicauth /settings* {
    birdnet ${HASHWORD}
  }"
    else
        AUTH_BLOCK=""
    fi
    
    # Create new Caddyfile
    cat << EOF | sudo tee /etc/caddy/Caddyfile > /dev/null
# BirdNET-Pi Caddy Configuration
# Generated by install_web.sh on $(date)

{
    admin off
}

http:// ${BIRDNETPI_URL:-} {
    # FastAPI backend serves API and frontend
    reverse_proxy localhost:8080
    ${AUTH_BLOCK}
    
    # Live audio stream (Icecast)
    handle /stream* {
        reverse_proxy localhost:8000
    }
    
    # Log viewer (gotty)
    handle /log* {
        reverse_proxy localhost:8081
    }
    
    # Terminal (gotty)  
    handle /terminal* {
        reverse_proxy localhost:8888
    }
    
    # Streamlit stats (if still used)
    handle /stats* {
        reverse_proxy localhost:8501
    }
    
    # Compression
    encode gzip
    
    log {
        output file /var/log/caddy/birdnet.log {
            roll_size 10mb
            roll_keep 5
        }
    }
}
EOF

    # Create log directory
    sudo mkdir -p /var/log/caddy
    sudo chown caddy:caddy /var/log/caddy
    
    echo_info "Caddy configuration updated"
}

disable_php_services() {
    echo_step "Disabling PHP services (migration)..."
    
    # Stop and disable PHP-FPM if running
    for service in $(systemctl list-units --type=service --state=running | grep php | awk '{print $1}'); do
        echo_info "Stopping $service"
        sudo systemctl stop "$service" || true
        sudo systemctl disable "$service" || true
    done
    
    echo_info "PHP services disabled"
}

resolve_port_conflicts() {
    echo_step "Checking for service port conflicts..."

    # Legacy installs may have birdnet_log bound to 8080, which conflicts with birdnet-web.
    if sudo systemctl is-enabled birdnet_log &>/dev/null || sudo systemctl is-active birdnet_log &>/dev/null; then
        if sudo systemctl cat birdnet_log 2>/dev/null | grep -q -- "-p 8080"; then
            echo_warn "Detected legacy birdnet_log on port 8080; migrating it to 8081."
            unit_path=$(sudo systemctl show -p FragmentPath --value birdnet_log 2>/dev/null || true)
            if [ -n "$unit_path" ] && [ -f "$unit_path" ]; then
                sudo sed -i 's/-p 8080/-p 8081/g' "$unit_path"
                sudo systemctl daemon-reload
                sudo systemctl enable birdnet_log || true
                sudo systemctl restart birdnet_log || true
            else
                echo_warn "Could not locate birdnet_log unit file; disabling service to prevent conflict."
                sudo systemctl stop birdnet_log || true
                sudo systemctl disable birdnet_log || true
            fi
        else
            # Ensure logs service is running if configured on a non-conflicting port.
            sudo systemctl restart birdnet_log || true
        fi
    else
        # If service exists but is disabled, leave as-is.
        if sudo systemctl list-unit-files | grep -q "^birdnet_log.service"; then
            :
        else
            # No legacy service found; nothing to resolve.
            :
        fi
    fi

    # Explicitly guard against any other listener on 8080 before starting birdnet-web.
    if command -v lsof >/dev/null 2>&1; then
        if sudo lsof -nP -iTCP:8080 -sTCP:LISTEN 2>/dev/null | grep -v "uvicorn" | grep -q .; then
            echo_warn "A process is already listening on port 8080; attempting to continue may fail."
            sudo lsof -nP -iTCP:8080 -sTCP:LISTEN 2>/dev/null || true
        fi
    fi
}

verify_directories() {
    echo_step "Verifying directory structure..."
    
    # Source config to get directory paths
    source "$CONFIG_FILE" 2>/dev/null || true
    
    # Set defaults if not defined
    RECS_DIR="${RECS_DIR:-$HOME/BirdSongs}"
    EXTRACTED="${EXTRACTED:-$HOME/BirdSongs/Extracted}"
    
    # Create required directories
    mkdir -p "${EXTRACTED}/By_Date" 2>/dev/null || true
    mkdir -p "${EXTRACTED}/Charts" 2>/dev/null || true
    
    # Verify database exists; fail safe if missing to avoid silent empty migrations
    if [ ! -f "$BIRDNET_DIR/scripts/birds.db" ]; then
        echo_error "Database not found at $BIRDNET_DIR/scripts/birds.db"
        echo_error "Aborting to avoid an accidental empty migration."
        echo_error "Restore birds.db from backup, or run createdb.sh intentionally if this is a fresh system."
        return 1
    fi
    
    echo_info "Directory structure verified"
}

check_password_config() {
    echo_step "Checking authentication configuration..."
    
    source "$CONFIG_FILE" 2>/dev/null || true
    
    if [ -z "${CADDY_PWD}" ]; then
        echo ""
        echo_warn "No password is configured for the web interface settings."
        echo_warn "The Settings page requires authentication to prevent unauthorized changes."
        echo ""
        read -p "Would you like to set a password now? [Y/n] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            read -s -p "Enter password for 'birdnet' user: " NEW_PWD
            echo
            if [ -n "$NEW_PWD" ]; then
                # Update config file
                if grep -q "^CADDY_PWD=" "$CONFIG_FILE"; then
                    sudo sed -i "s/^CADDY_PWD=.*/CADDY_PWD=\"$NEW_PWD\"/" "$CONFIG_FILE"
                else
                    echo "CADDY_PWD=\"$NEW_PWD\"" | sudo tee -a "$CONFIG_FILE" > /dev/null
                fi
                echo_info "Password configured successfully"
            else
                echo_warn "Empty password entered, skipping"
            fi
        else
            echo_warn "Skipping password setup. You can set CADDY_PWD in $CONFIG_FILE later."
        fi
    else
        echo_info "Password already configured"
    fi
}

start_services() {
    echo_step "Starting services..."
    
    # Reload and restart Caddy
    sudo systemctl reload caddy || sudo systemctl restart caddy
    
    # Start the new web service
    sudo systemctl start birdnet-web
    
    # Verify it's running
    sleep 2
    if sudo systemctl is-active --quiet birdnet-web; then
        echo_info "Web service started successfully"
    else
        echo_error "Web service failed to start"
        echo_error "Check logs with: sudo journalctl -u birdnet-web -n 50"
        return 1
    fi
}

run_base_install() {
    echo_step "Running base BirdNET-Pi installation..."
    
    # Run the existing installation scripts
    cd "$BIRDNET_DIR/scripts"
    
    # Install config if needed
    if [ ! -f "$CONFIG_FILE" ]; then
        ./install_config.sh
    fi
    
    # Source config
    source "$CONFIG_FILE"
    
    # Install services (but we'll modify for new web interface)
    # We need to skip PHP-specific parts
    export SKIP_PHP=1
    sudo -E HOME=$HOME USER=$USER ./install_services.sh
    
    # Install Python environment
    cd "$BIRDNET_DIR"
    if [ ! -d "birdnet" ]; then
        echo_info "Creating Python virtual environment..."
        python3 -m venv birdnet
        source ./birdnet/bin/activate
        pip3 install wheel
        pip3 install -r ./requirements.txt
    fi
    
    # Install language labels
    cd "$BIRDNET_DIR/scripts"
    ./install_language_label.sh || true
    
    echo_info "Base installation complete"
}

# Main installation logic
main() {
    echo ""
    echo "=============================================="
    echo "   BirdNET-Pi Web Interface Installer"
    echo "=============================================="
    echo ""
    
    # Detect installation state
    if is_fresh_install; then
        echo_info "Detected: Fresh installation"
        INSTALL_MODE="fresh"
    elif has_new_web_interface; then
        echo_info "Detected: New web interface already installed"
        echo_warn "Re-running will rebuild the frontend and restart services"
        INSTALL_MODE="update"
    elif is_base_installed; then
        if is_php_installed; then
            echo_info "Detected: Migration from PHP interface"
            INSTALL_MODE="migrate"
        else
            echo_info "Detected: Base installed, adding web interface"
            INSTALL_MODE="add"
        fi
    else
        echo_error "BirdNET-Pi base system not found"
        echo_error "Please run the base installer first or set BIRDNET_DIR"
        exit 1
    fi
    
    echo ""
    echo "Installation mode: ${INSTALL_MODE}"
    echo ""
    
    # Confirm with user
    read -p "Continue with installation? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "Installation cancelled"
        exit 0
    fi
    
    # Run appropriate installation steps
    case "$INSTALL_MODE" in
        fresh)
            echo_warn "Fresh install requires running the base installer first"
            echo_info "Please run: ./scripts/install_birdnet.sh"
            echo_info "Then run this script again"
            exit 1
            ;;
        migrate)
            # Migration from PHP
            verify_directories
            check_password_config
            install_nodejs
            install_backend_deps
            build_frontend
            install_systemd_service
            disable_php_services
            resolve_port_conflicts
            update_caddy_config
            start_services
            ;;
        add|update)
            # Add web interface or update existing
            verify_directories
            check_password_config
            install_nodejs
            install_backend_deps
            build_frontend
            install_systemd_service
            resolve_port_conflicts
            update_caddy_config
            start_services
            ;;
    esac
    
    # Success message
    echo ""
    echo "=============================================="
    echo_info "Installation complete!"
    echo ""
    
    # Get IP address
    IP_ADDR=$(hostname -I | awk '{print $1}')
    echo "Access your BirdNET-Pi at:"
    echo "  http://${IP_ADDR}"
    echo "  http://$(hostname).local"
    echo ""
    
    if [ "$INSTALL_MODE" == "migrate" ]; then
        echo_warn "PHP services have been disabled."
        echo_warn "If you need to revert, restore /etc/caddy/Caddyfile.backup.*"
    fi
    
    # Check if password was configured
    source "$CONFIG_FILE" 2>/dev/null || true
    if [ -z "${CADDY_PWD}" ]; then
        echo ""
        echo_warn "Note: No password configured. Settings page will be inaccessible."
        echo_warn "To enable settings, set CADDY_PWD in $CONFIG_FILE and restart birdnet-web"
    else
        echo ""
        echo "Settings page login: username 'birdnet'"
    fi
    
    echo "=============================================="
}

# Run main
main "$@"
